### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by julioz** [sourcegraph/zoekt#236]
It would be great to have a small excerpt in the README of the project (or similar) with a few examples on how to interact with the exposed API (via rpc and/or stream endpoints).

Something as simple as `curl` commands would make it easier to onboard other folks to the project and make it easier to get started on integrations to zoekt.

**Comment by keegancsmith** [comment]
Agreed, we should update the docs here a bit with our changes. Note: the current API isn't regarded as stable, since we are often iterating on types/etc currently. However, the stream endpoints are relatively stable. cc @stefanhengl

**Comment by stefanhengl** [comment]
The project's README.md now contains an example of a `curl` call to the webserver.
