### ISSUE TITLE
provide option to make zoekt-git-index run deterministically

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/zoekt#276]
zoekt-git-index sets a timestamp which eventually becomes part of the shard. Some of our tests would profit from zoekt-git-index being deterministic. For example, the recently added "zoekt-merge-index explode"  could be tested by comparing the input of "zoekt-merge-index merge" with the output of "zoekt-merge-index explode" byte by byte.

**Comment by keegancsmith** [comment]
Did we add anything like this? I think we may have internally added a way to do this to the build.Options struct, but maybe we need a flag to the cli?

**Comment by stefanhengl** [comment]
We can close this. The flag is not needed if we stick to unit tests. See #279
