### ISSUE TITLE
Add Datadog tracer & profiler

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/zoekt#294]
Hello team!

Could I ask that you all add the Datadog tracing library and profiler when you get a chance? 

Some relevant PRs for how we added this to Sourcegraph: 
https://github.com/sourcegraph/sourcegraph/pull/32020
https://github.com/sourcegraph/sourcegraph/pull/31294

Happy to do myself eventually but it would likely be quicker with those more familiar with the codebase. 

Related to https://github.com/sourcegraph/sourcegraph/issues/30699

**Comment by tsenart** [comment]
@daxmc99: It's not different from the other services, [just a different function to update](https://sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/zoekt%24+profiler&patternType=literal) with the Datadog profiler. We'll be happy to review a PR.
