### ISSUE TITLE
zoekt-index gets stuck when indexing some files from a local AOSP repo

### ISSUE THREAD

**Issue by enalvarez** [sourcegraph/zoekt#353]
Hi!

I'm trying to index an AOSP local repo with `zoekt-index` but it gets stuck when indexing some files. These files, as I could see, are some test XML with a bad encoding or other XML with rare chars. 

In the process list I see that ctags has the state `<defunct>` when these files are indexed. Indexing these files individually has the same result.

The full command that I'm executing with one of these files is:
`zoekt-index -index ./indexes/ -shard_limit 50000000 -max_trigram_count 40000 ./aosp/external/libxml2/result/ebcdic_566012.xml`

And the ctags process is now a zombie:
![image](https://user-images.githubusercontent.com/23578899/170432333-3205506c-e978-46c2-af98-f8ba1d373ac2.png)

I'm using the last version of zoekt and ctags.

Thank you! 

PS: Some sample files that produce the error
![userprefs-badencoding xml](https://user-images.githubusercontent.com/23578899/170435983-00c39f12-a61d-4d1a-ae1a-4a567cfa8035.png)
![ebcdic_566012 xml](https://user-images.githubusercontent.com/23578899/170435988-ebc5bb45-8526-4b8c-98eb-c3b67ddd0c86.png)

**Comment by keegancsmith** [comment]
Can you share a link to the file? Can you ensure you have the latest versions of zoekt installed from this repo? IE run something like `go install ./cmd/zoekt-*` from a checkout of this repo. The reason I ask this is we should only be passing in files that have a valid utf8 encoding: https://github.com/sourcegraph/go-ctags/blob/f974026334d737798826bad800a935ee2620ecfa/ctags.go#L223-L228

**Comment by enalvarez** [comment]
You can take the example files from these links:
- https://android.googlesource.com/platform/external/libxml2/+/refs/heads/master/result/ebcdic_566012.xml
- https://android.googlesource.com/platform/libcore/+/refs/heads/master/luni/src/test/resources/prefs/java/util/prefs/userprefs-badencoding.xml

Ok, I'll try with the checkout of this repo and I'll tell you the results.

Thanks!

**Comment by enalvarez** [comment]
I've tried to install the version as you told me, and it works. I was using indeed the installation described in the README file.

Thank you so much!! :)
