### ISSUE TITLE
Feature request: filtering on whether code is in an archived repository

### ISSUE THREAD

**Issue by jamespwilliams** [sourcegraph/zoekt#368]
Gitlab and GitHub have the concept of *archived* repositories (and possibly other sources zoekt can use, but I haven't used the others). In many organisations, archived repositories contain code which is not currently in use, but is kept for future reference. When searching code, archived repositories are often no longer relevant. It would be nice to be able to ignore results in these repositories.

In an ideal world, I'd be able to include a search term such as `archived:no` to filter out results in archived repositories (and, similarly, `archived:yes` would filter out results in non-archived repositories).

If this feature is something that you'd be interested in adopting, I may try and implement it myself.

**Comment by stefanhengl** [comment]
Can you explain a bit more about your use-case? How do you mirror your repos?  

Background:
- Sourcegraph uses Zoekt as backend for indexed search. Together with Sourcegraph, Zoekt already supports "archived".
- With zoekt-mirror-github, native Zoekt has a flag `no_archived` that excludes archived repos from being mirrored

**Comment by jamespwilliams** [comment]
We use zoekt-mirror-gitlab.

The situation that made me file this issue was as follows: I was using zoekt to search for all instances of a particular constant being used, so I could find where it needed to be updated after its name was changed. Archived repos aren’t relevant in this case, because they can’t be changed, so I wanted to exclude them from the search.

I don’t really like the solution of stopping mirroring archived repos, because searching archived repos can be useful in many cases. Ideally I’d like to be able to make the choice of whether to include archived repos at search time.

**Comment by stefanhengl** [comment]
Alright, that makes sense. Feel free to open a PR and we will take a look!

Some guidance:

We should support the other mirrors too and the design should be compatible with how we store "archived" for repos mirrored from Sourcegraph.

Here is some prior art:

We use the `RawConfig` query type to filter for "archived":
https://sourcegraph.com/github.com/sourcegraph/zoekt@a174ad6/-/blob/query/query.go?L52:4&subtree=true

This is how we store the flag "archived" coming from Sourcegraph in the git config
https://sourcegraph.com/github.com/sourcegraph/zoekt@a174ad6993a841532c20b2ab9d817c715beffa5a/-/blob/cmd/zoekt-sourcegraph-indexserver/index.go?L295&subtree=true

**Comment by jamespwilliams** [comment]
Thanks for the pointers, I have opened https://github.com/sourcegraph/zoekt/pull/370.

**Comment by jamespwilliams** [comment]
Fixed in #370
