### ISSUE TITLE
Update of the zoekt go module(s)

### ISSUE THREAD

**Issue by henrik242** [sourcegraph/zoekt#378]
It seems like the `github.com/google/zoekt` go module is not updated, and I can't get `github.com/sourcegraph/zoekt` to work.
```
go: github.com/sourcegraph/zoekt@latest: github.com/sourcegraph/zoekt@v0.0.0-20220621072411-5c27ec2fb1a2: parsing go.mod:
	module declares its path as: github.com/google/zoekt
	        but was required as: github.com/sourcegraph/zoekt
```

The sourcegraph zoekt docker image does have the latest changes, though.

Are there plans on updating the go modules too?

**Comment by keegancsmith** [comment]
We didn't have any plans here, but we are starting to diverge enough from upstream zoekt that we should probably just declare we are a hard fork and rename the module. @sourcegraph/search-core WDYT?

**Comment by henrik242** [comment]
@keegancsmith That would be really appreciated! There might be an issue with using indexes made with the google/zoekt go modules that can't be used with sourcegraph/zoekt docker image.

**Comment by henrik242** [comment]
@keegancsmith Any updates to this?

**Comment by keegancsmith** [comment]
I've been out of office, but will bring it up.

**Comment by henrik242** [comment]
Cool, I see that you [committed some changes](https://github.com/sourcegraph/zoekt/commit/5ee92f5abab3047f8b36172f31e49a4922dedc27) in that regard yesterday.  It's still not perfect though (from docker build with go 1.18):
```
 > [2/7] RUN go install github.com/sourcegraph/zoekt@latest:                                                                                                                                                                                                                                                                               
#5 65.09 package github.com/sourcegraph/zoekt is not a main package
```

**Comment by keegancsmith** [comment]
Yup this is all working now. sourcegraph/zoekt is not a main package. If you want to install something you need to pick a command like `github.com/sourcegraph/zoekt/cmd/zoekt`
