### ISSUE TITLE
Language buttons don’t work with multi-word language names

### ISSUE THREAD

**Issue by jamespwilliams** [sourcegraph/zoekt#388]
It’s possible for language names displayed in zoekt results to contain whitespace, e.g: “DIGITAL Command Language”, or “DNS Zone File”.

Taking “DNS Zone File” as an example, when you click the “language DNS Zone File” button, you end up with `lang:DNS Zone File`, which searches for “Zone File” in files of language “DNS”. Instead, the search term should be `lang:"DNS Zone File"`.

I think ideally the language term should only be quoted when necessary, so for single-word languages quotes still shouldn’t be used. That way queries are still as concise as possible.

I’ll probably have a go fixing this myself when I get time.

**Comment by stefanhengl** [comment]
@jamespwilliams This should be fixed with #478. Please reopen this issue if you still encounter errors.
