### ISSUE TITLE
RPC: support non-gob encodings?

### ISSUE THREAD

**Issue by isker** [sourcegraph/zoekt#410]
Hi.  I'd like to slap an alternative web UI on zoekt (example motivations: instant search, like livegrep; syntax highlighting in the builtin file viewer; alternative homepage suitable to my particular deployment).  The APIs exposed in web (when passing `format=json`) don't seem sufficient to do this.  For example, there doesn't seem to be a way to list repositories, or to retrieve full file contents.

Both of those things are provided by rpc/.  But rpc only speaks gob.  It seems the only way to use rpc from not-go is to proxy it with go, translating into something that's not gob.  I could do that, but it feels like a waste.  Ideally there would be a way to serve another more portable encoding (JSON seems like the least controversial option).

I'm no go expert, but it doesn't seem trivial to serve JSON instead of gob, in the way that it is to serve JSON instead of HTML in web, because rpc directly uses `net/rpc` (or, your fork of it), which precludes alternative encodings.  Does that sound correct?

Thanks!

**Comment by keegancsmith** [comment]
You can use the normal endpoint that is returned by `search` and make it return json if you pass in the appropriate accept header. That should be more straight forward to do. EG do some json encoding around this point: https://github.com/sourcegraph/zoekt/blob/main/web/server.go#L215-L219

**Comment by keegancsmith** [comment]
@isker I just noticed that you can add `format=json` to the endpoint. So we support this already :)

**Comment by isker** [comment]
@keegancsmith I'm specifically saying that the JSON API available at the search endpoint here https://github.com/sourcegraph/zoekt/blob/26bbd7bcbb07ad767d8fc1069b6c7ef40460bc0c/web/server.go#L207-L212 is pretty limited compared to the gob API available here https://github.com/sourcegraph/zoekt/blob/main/rpc/rpc.go.

> For example, there doesn't seem to be a way to list repositories, or to retrieve full file contents.

Compare https://github.com/sourcegraph/zoekt/blob/26bbd7bcbb07ad767d8fc1069b6c7ef40460bc0c/api.go#L275-L287 which is only available in gob, to https://github.com/sourcegraph/zoekt/blob/26bbd7bcbb07ad767d8fc1069b6c7ef40460bc0c/web/api.go#L23-L26 which is available in JSON.

**Comment by keegancsmith** [comment]
I see, thanks. It seems like we should add a way to just json dump the full type as present in api.go? I'm happy to review a PR adding that.

**Comment by isker** [comment]
> I see, thanks. It seems like we should add a way to just json dump the full type as present in api.go? I'm happy to review a PR adding that.

Yes, but I'm not sure how to do that easily when ~net~keegansmith/rpc is in the driver's seat:

https://github.com/sourcegraph/zoekt/blob/00761158b06d4aab579d26d1e0bca5d36e43ccc7/rpc/rpc.go#L23-L33

Thoughts?  This doesn't seem like it'd be an appropriate extension to put in your rpc fork.

Do you think this should be a separate API on yet-another port, or should we try to find a way to make this work on the existing port and let clients opt-in to JSON with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept ?

**Comment by isker** [comment]
Sorry, those questions are mostly nonsense, because I misunderstood how things work:  we don’t use a different port for gob rpc, just a particular path (/rpc by default).  So I think JSON renditions of Search and List should just be at different paths. (Suggestions on those welcome 🌞.)

I will take a shot at an MR for this in a few days.
