### ISSUE TITLE
Native implementation of repohasfile:

### ISSUE THREAD

**Issue by cursedcoder** [sourcegraph/zoekt#433]
Hi, have you thought about adding `repohasfile:` syntax here?

If yes, what do I need to know before submitting PRs for this?

**Comment by keegancsmith** [comment]
That exists, but not with that syntax. You can use `type:repo` to limit results to matching repos. eg to look for the word `kubernetes` in all repos containing a `Dockerfile` you can use a query like `(type:repo file:dockerfile) kubernetes`
