### ISSUE TITLE
`Content` missing trailing empty lines (with NumContextLines > 0)

### ISSUE THREAD

**Issue by isker** [sourcegraph/zoekt#524]
I'm seeing a bit of a weird bug in context in ChunkMatches' Content in the JSON API that, as far as I can tell, is not specific to the JSON API:

1. Checkout latest `main`
2. `go run cmd/zoekt-git-index/main.go -index zoekt-index  -require_ctags .`
3. `go run cmd/zoekt-webserver/main.go -html=false -rpc=true -index zoekt-index`
4. `curl -sX POST -d'{"q": "testing f:^eval_test.go", "opts": {"ChunkMatches": true, "NumContextLines": 1}}' localhost:6070/api/search | jq -r '.Result.Files[0].ChunkMatches[0].Content' | base64 --decode`
The output you get has only two lines; there is no trailing line of context:
```
	"strings"
	"testing"
```
Taking `ChunkMatches[1].Content` correctly gives output with three lines:
```

func printRegexp(t *testing.T, r *syntax.Regexp, lvl int) {
	t.Logf("%s%s ch: %d", strings.Repeat(" ", lvl), opnames[r.Op], len(r.Sub))
```

It seems to be that whenever the final context line is empty (i.e. `\n\n`), the final newline character is missing from `Content`.

Viewing [the same query on sourcegraph](https://sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/zoekt%24+testing+f:%5Eeval_test.go&patternType=standard&sm=1&groupBy=path) shows the proper context for the first match:
<img width="715" alt="Screenshot 2023-01-29 at 01 25 09" src="https://user-images.githubusercontent.com/5225653/215309059-78e47ef9-3285-4d34-a3c2-b992c3d737c9.png">
I say that I don't think this is related to the JSON API in particular because print debugging `Content` values before they're serialized shows that the above example simply only has one trailing newline when it should have two.  I'd expect the net/rpc API to have the same problem if I had an easy way to interactively query it.  But, sourcegraph has the right data, so maybe that expectation is not correct?

**Comment by keegancsmith** [comment]
Thanks for the detailed bug report. This does indeed sound like a problem in zoekt-webserver rather than the core zoekt searcher. @gl-srgr you taking this?

**Comment by isker** [comment]
This is not specific to zoekt-webserver.

Checkout https://github.com/isker/zoekt/tree/%23524-repo, where I've rewritten main.go to use the RPC client.  Reproduce like this:

1. `go run cmd/zoekt-git-index/main.go -index zoekt-index  -require_ctags .`
2. `go run cmd/zoekt-webserver/main.go -html=false -rpc=true -index zoekt-index`
3. `go run cmd/zoekt/main.go -- 'testing f:^eval_test.go'`

Output:
```
~/zoekt #524-repo• λ go run cmd/zoekt/main.go -- 'testing f:^eval_test.go'
	"strings"
	"testing"
~/zoekt #524-repo• λ    
```

So, is sourcegraph.com using ChunkMatches?  Is it papering this problem over in the rpc client?

**Comment by isker** [comment]
As far as I can tell it's a bug somewhere in [`fillContentChunkMatches`](https://github.com/sourcegraph/zoekt/blob/f497f219d3573d2c6fd22e4e4aed1cd42ed30f39/contentprovider.go#L285).

I do note this doc comment on `lineBounds` which may be describing an aspect of the bug:
https://github.com/sourcegraph/zoekt/blob/f497f219d3573d2c6fd22e4e4aed1cd42ed30f39/contentprovider.go#L413-L417
> **and will not contain the line-ending newline**

I'd try to add a test case reproducing this problem but as far as I can see there is no existing test coverage on any methods of `contentProvider`.  That is a nasty struct; looks like it would take a lot of time to manually write an instance of it.  All of the test coverage is on `newlines` or pure functions 😞.

**Comment by isker** [comment]
... maybe this isn't a bug 😄.  I think I've just misunderstood how the search API works the entire time:

```
# One trailing newline, as already demonstrated
~ λ echo -n '{"q": "testing f:^eval_test.go", "opts": {"ChunkMatches": true, "NumContextLines": 1}}' | xh POST localhost:6070/api/search | jq -r .Result.Files[0].ChunkMatches[0].Content | base64 --decode
	"strings"
	"testing"
# Zero trailing newlines!
~ λ echo -n '{"q": "cmp f:^eval_test.go", "opts": {"ChunkMatches": true, "NumContextLines": 1}}' | xh POST localhost:6070/api/search | jq -r .Result.Files[0].ChunkMatches[0].Content | base64 --decode
	"github.com/RoaringBitmap/roaring"
	"github.com/google/go-cmp/cmp"
	"github.com/grafana/regexp"⏎
~ λ
```

(The `⏎` character in that output indicating "no trailing newline".)

I had thought that `Content` was always including a trailing newline in all search results, so `Content` ending in an empty line should have two trailing newlines.  But that's totally wrong, as the above requests indicated; zero is the norm.  So, there's no problem.  Sorry if anybody spent time trying to understand this 🙃.

**Comment by keegancsmith** [comment]
:D no worries. Thanks for the detailed dive in :)
