### ISSUE TITLE
gob: type regexp.Regexp has no exported fields - using List with `repo:` in RPC

### ISSUE THREAD

**Issue by xvandish** [sourcegraph/zoekt#563]
Hello!

I set up a Go service that imports/uses the RPC client, something like this

```
package whatever
import (
        ...
	"github.com/sourcegraph/zoekt/query"
	"github.com/sourcegraph/zoekt/rpc"
)
func (s *Server) handleSearch(w.....) {
  searchQ := searchForm.Q

  q, err := query.Parse(searchArgs.Q)

  
  repoOnly := true
  query.VisitAtoms(q, ...) // decide if repoOnly

  if (repoOnly) { 
    s.Searcher.List(ctx, q, opts)
  }
  ...
}

func main() {
  client := rpc.Client(*rpcConnect) 

  mux.Handle("/api/search", handleSearch)
  ...
}
```

However, whenever the query request is `repoOnly`, like for example, `repo:test`, the request to the rpc server fails with:

`Search failed, HTTP 500: Internal Server Error - {"Error":"gob: type regexp.Regexp has no exported fields"}`.

I get what the error is saying, but not why it's happening/how Sourcegraph gets around it. 

Things I've tried/checked:

1. Made sure that the call to `rpc.RegisterGob` was getting called on webserver initialization 
2. run `query.Simplify()` on the query
4. encoded `RepoRegex` query directly, like so: `s.Searcher.List(ctx, &query.RepoRegexp{Regexp: re}, opts)`, using the `grafana/regex` package. This works, somehow?
5. Imported and used grafana/regexp package for something else, but still used `q` in the call to List. This fails. (I was thinking somehow a conflict between the grafana & stdlib regexp packages was happening..)
6. encoded `Repo` query directly, like so: `s.Searcher.List(ctx, &query.Repo{Regexp: re}, opts)`, using the `grafana/regex` package. This failed!
7. Looked into some of the `.List()` calls in `sourcegraph/sourcegraph` to see if I was missing anything obvious, didn't see anything.

Am I doing anything wrong here? As far as I can tell, both `RepoRegexp` and `Repo` are gob encoded, so not sure why one works and the other doesn't. It's late, I'll take a fresh look tomorrow but would appreciate a look at this. Thanks!

**Comment by keegancsmith** [comment]
Looks like your PR should resolve this. Thanks for digging in!

**Comment by xvandish** [comment]
Thanks for taking a look & reviewing!
