### ISSUE TITLE
replace directive in go.mod breaks `go install github.com/sourcegraph/zoekt/cmd/zoekt@latest`

### ISSUE THREAD

**Issue by henrik242** [sourcegraph/zoekt#643]
Commit 3ce1f2b breaks `go install github.com/sourcegraph/zoekt/cmd/zoekt@latest` by introducing a [replace directive](https://github.com/sourcegraph/zoekt/commit/3ce1f2b24c80b3dea89d237600d2b0879342ed1b#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R152) in go.mod.

The error I get is:
```
go: github.com/sourcegraph/zoekt/cmd/zoekt@latest (in github.com/sourcegraph/zoekt@v0.0.0-20230912152407-3ce1f2b24c80):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Replace directives [can be problematic](https://github.com/golang/go/issues/44840#issuecomment-967294447) for users. Is there a suggested workaround for this?

**Comment by keegancsmith** [comment]
cc @ggilmore
