### ISSUE TITLE
`Repository.MergeMutable` doesn't handle changes to *Template fields

### ISSUE THREAD

**Issue by isker** [sourcegraph/zoekt#683]
Hi.  I changed the `CommitURLTemplate` on some (non-git!) repos we are indexing and noted that they did not get reindexed with the new template.  This is because changes to that field (and related ones) are not being handled in `Repository.MergeMutable`:

https://github.com/sourcegraph/zoekt/blob/bec12a772b51bd06a65ca4dd58d0eb348033b313/api.go#L654

@keegancsmith (since you're on blame 🌞) would Sourcegraph be negatively impacted if they were?  Is there any reason to not add these?

**Comment by keegancsmith** [comment]
Yes we can add these, it should be completly fine. If it isn't fine, we should make it fine for sourcegraph.

**Comment by isker** [comment]
Great, I will file a PR some time.
