### ISSUE TITLE
zoekt-sourcegraph-indexserver doesn't visit local bare repositories

### ISSUE THREAD

**Issue by xavier-calland** [sourcegraph/zoekt#762]
When using zoekt-sourcegraph-indexserver with a local directory for `sourcegraph_url` , it doesn't index bare repositories.

As I understand, this comes from the `visitRepos` function searching for `.git` folders.

https://github.com/sourcegraph/zoekt/blob/ab1b8f09199ea7a731fd80876fc5b0f376ff6882/cmd/zoekt-sourcegraph-indexserver/sg.go#L727

It would be nice to have the same behaviour as some commands like `zoekt-git-index`.

**Comment by keegancsmith** [comment]
indexing a local dir in that command is purely for debug/development. Will likely never get to implementing since it support the use case for dev, so gonna close this out.

**Comment by xavier-calland** [comment]
OK, I see.
I want to index all repositories on a Gerrit server automatically (periodic fetch and index)?
It seems that directly indexing the folder containing the bare repositories with zoekt-sourcegraph-indexserver is not the right solution.
What do you think is the best approach to do this? Maybe with zoekt-indexserver?

**Comment by keegancsmith** [comment]
Yes I believe zoekt-indexserver was designed for that.
