### ISSUE TITLE
zoekt-mirror-gerrit doesn't pass credentials to git clone

### ISSUE THREAD

**Issue by xavier-calland** [sourcegraph/zoekt#763]
When using credentials `zoekt-mirror-gerrit` with http credentials.

Credentials are used when calling Gerrit API but are _lost_ when executing `git clone`.

That's because `cloneURL` uses `projectURL` which doesn't contain the http password but only the username (unlike `rootURL`).

**Comment by keegancsmith** [comment]
Happy to review a PR here.

**Comment by xavier-calland** [comment]
Ok, I'll try to do a PR.
Do you have any advice before I start?

**Comment by keegancsmith** [comment]
Check if the API includes a clone URL. For best use of zoekt-mirror-gerrit maybe @hanwen has advice :)

**Comment by hanwen** [comment]
from a quick look (it's been a while), the clone command is just using what Gerrit provides as the clone URL. You'd have to set a User field on the cloneURL. Alternatively, find a way to configure the HTTP credential in the Git credential helper.
