### ISSUE TITLE
zoekt-indexserver - Prune branches when fetching git repository

### ISSUE THREAD

**Issue by xavier-calland** [sourcegraph/zoekt#768]
`zoekt-indexserver` fetches the git repository to have an up-to-date repository with all branches.
https://github.com/sourcegraph/zoekt/blob/6df055493b1600051e467b79d296fa292f658d3f/cmd/zoekt-indexserver/main.go#L131-L132

When a branch is deleted in the repository, it still exists in the index because fetch does not prune deleted branches.

Adding the `--prune` parameter to the fetch command guarantees an up-to-date list of branches

```go
cmd := exec.Command("git", "--git-dir", dir, "fetch", "origin", "--prune") 
```

**Comment by keegancsmith** [comment]
FYI you don't need to file an issue first if you have already diagnosed the code problem, feel free to just send a PR :)

**Comment by xavier-calland** [comment]
:ok_hand:  :slightly_smiling_face:

**Comment by isker** [comment]
@keegancsmith @xavier-calland looks like one of you ought to close this?

And #763 too.
