### ISSUE TITLE
feature request: option for opening search results in a new tab by default

### ISSUE THREAD

**Issue by krisdock** [sourcegraph/zoekt#787]
we're using zoekt within an iframe in our developer portal, but github results can't be opened directly because gh blocks framing. having the option to set "resultLinksNewTab" (or something) would be awesome.

**Comment by keegancsmith** [comment]
We won't add a specific option for this. However, we already support completely changing the templates used for every page. So the way to do this would be to specify the `-template_dir` argument to zoekt-webserver. You can dump the default templates (so you can modify them) with `-dump_templates` argument.
