### ISSUE TITLE
Is the maximum response time for a search 10 seconds?

### ISSUE THREAD

**Issue by bonohubby** [sourcegraph/zoekt#857]
Hello, I am testing Zoekt to see if it can provide source code search for large-scale codebases such as 100GB, 1TB, or even larger.

It seems natural that the search time increases as the search scale grows, but it appears that the response is always provided within 10 seconds, regardless of the scale. I am curious about how Zoekt manages to provide search results within this time frame and whether it is possible to adjust this maximum response time to something like 5 seconds.

Thank you for providing Zoekt.

**Comment by keegancsmith** [comment]
For zoekt-webserver (which I assume you are using) it is hardcoded at https://github.com/sourcegraph/zoekt/blob/4f038fd84b02188dfaebf0fb9570325868e7ca55/web/server.go#L291-L293

If you are hitting that 10s mark it means your search is not exhaustive (it it hasn't finished searching the full corpus). However, it will likely have found a bunch of candidate documents that it has then ranked and truncated to what we display.

Zoekt can scale to large repositories, at indexing time it chunks up repositories into 100mb of code then treats each of those bits as independent. You may run into vertical scaling issues at some point. In that case there isn't actually any code for horizontal scaling in this repository. However, there is relatively simple code for horizontal aggregation code which you can find with an OSS license in older versions of the Sourcegraph repo. For reference Sourcegraph host far more than 100GB on a single node, but it can take longer than 10s depending on the query.

**Comment by bonohubby** [comment]
Thank you for your kind response 😄
