### ISSUE TITLE
Why does the parser not support explicit and keyword?

### ISSUE THREAD

**Issue by KonradStanski** [sourcegraph/zoekt#860]
The way the parser is currently set up simplicity treats adjacent expressions as and, but requires explicit "or".
Sorry for creating noise, but I'm wondering if this is an explicit design choice? Would it be possible to add explicit and support?

I feel that this would make complicated queries / expressions much more readable and explicit.
It would also make penciling out the boolean algebra for convoluted searches much easier.

**Comment by keegancsmith** [comment]
I didn't write the original query parser, so I am spitballing a bit. I think treating spaces as `and` is an explicit design choice which makes constructing queries easy. Not supporting explicit `and` keywords seems like a reasonable choice to keep the language simple. I can see the downside that complicated queries written by humans may be hard to read, but that is quite rare so seems like a reasonable trade-off. FYI if you are creating queries in code (via the query pkg) then of course ands are explicit.
